apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-uxpt
  namespace: jvm-build-mmku-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:4c40d254abe328475a00999f80dfdd5e12ac3a4fba6e50fac9837f66bf864668
        name: container-image
        resources: {}
status: {}
